services:
  redis:
    image: redis:7.4.0-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - redis-net
    volumes:
      - redis_data:/data
      - redis.conf:/etc/redis/redis.conf
    command:
      redis-server /etc/redis/redis.conf
volumes:
  redis_data:
    driver: local
  redis.conf:
    driver:
      local
networks:
  redis-net:
    name:
      redis-net
